import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import ProfileNav from "../src/Components/shared/ProfileNav";
import MainDashboard from "../src/Components/MainDashboard";
import { Container, Row } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>React Medassist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="main_bg rounded">
        <Row className="p-3">
          <ProfileNav />
          <MainDashboard />
        </Row>
      </Container>
    </>
  );
}
